### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by rsmck** [magdesign/PocketVJ-CP-v3#104]
Sorry, this is not related to the codebase but the website is down and this seemed to be the only way to contact you as I was not able to find an email address for you on magdesign.ch.

is PocketVJ still around?

**Comment by magdesign** [comment]
sorry, i am switching server but have limited internet access in the moment.

back online soon 🤞

**Comment by magdesign** [comment]
online again 😁

**Comment by BjarneJensen** [comment]
Hope all is well. I read that you're touring the countryside on bike and that the project is on hold. Hope the fresh air and exercise are treating you well! 

I had some trouble downloading the rtc image from the about page. Tried multiple times but failed. If I hit “resume download” enough times, I end up with a 611 mb file which seems small to me. When flashed, I get “kernel panic no working unit found”

Any chance this will be fixed in the future or is it just an artifact of my bad download? My internet speed seems fine. Thanks
