### ISSUE TITLE
other keyboard-commands in CP

### ISSUE THREAD

**Issue by navlisilvan** [magdesign/PocketVJ-CP-v3#2]
Hello,

i miss some keyboard-commands in the CP. For them there will be the extention Bord?

[Keys_PocketVJ-VP-v3.pdf](https://github.com/magdesign/PocketVJ-CP-v3/files/173133/Keys_PocketVJ-VP-v3.pdf)

for temperature-measurement you are using a adafruit DHT22?

thank you very much :)

**Comment by magdesign** [comment]
Key commands:
- Toggle fullscreen is not needed.
- Show info is also not needed.
- The arrow keys are replaced with 7; 8; 9; 0 (just updated, thanks for info).
- Deselect is missing, will integrate it soon, but I guess needs recompile since I dont know how to simulate other keys than numbers and letters...
- The extension will be free programmable for any function you want.

For temperature sensing, we use a LM75SO.

**Comment by magdesign** [comment]
Can you please test and report back.
I also dont know how exactly I can move in bigger steps.
May I link your pdf in the readme?

**Comment by navlisilvan** [comment]
Sorry for the delay, of cause you can.

[Keys_PocketVJ-VP-v3.pdf](https://github.com/magdesign/PocketVJ-CP-v3/files/188104/Keys_PocketVJ-VP-v3.pdf)

(i had to change the odt to docx. so you can change everything if necessary)

i didnt had the time to check eyerything yet.

**Comment by navlisilvan** [comment]
ok, docx is also not working in github.
[http://we.tl/KhmW1EoXPr](url)

**Comment by magdesign** [comment]
Thanks for providing the list, I put the link to the readme file.
Don't worry about the docx, I don't use MS office and I really hate proprietary formats. 
PDF or Openoffice is fine...
