### ISSUE TITLE
How to set the pi to use a static ip?

### ISSUE THREAD

**Issue by UnlimitedVideoStaging** [magdesign/PocketVJ-CP-v3#20]
Hi, I need my pvj 3.3 to use a specific ip address in the 192.168.101.* range.

I see the static and dhcp buttons, but how to set a specific static ip?

Thanks,

  Sean

**Comment by magdesign** [comment]
1. Open a webbrowser and type your PocketVJs IP followed by :4200 for example `2.0.0.100:4200 `
2. Your browser may complain about `Your connection is not private`, scroll down and click `Advanced`, and finally `Proceed to`.
3. Login with: `pi` 
4. Type: `sudo nano /etc/network/interfaces`
5. Navigate to` address 192.168.2.200` and change your value, remember to change `gateway 192.168.2.1` as well to your range.
6. Never change the IP of the wifi module, because it needs other settings as well!
7. reboot

**Comment by UnlimitedVideoStaging** [comment]
Thank you!
