### ISSUE TITLE
Seamless sync freezes when looping

### ISSUE THREAD

**Issue by mandelbrotmedia** [magdesign/PocketVJ-CP-v3#33]
I have 3 RPIs runing in master-slave seeamless sync mode. Everytime the master is looping the 2 slaves are freezing for 1-2 seconds.
Is tis normal?

**Comment by magdesign** [comment]
This is possibly normal, never tested so far. 
The old script made a 2 second black break, caused by killing omxplayer and starting a new one on each loop. The new script uses (in seamless mode) the --loop function of omxplayer to kinda rewind the movie. Since it takes longer for the master to rewind and start sending the timecode again, this might cause some kind of "race condition". I will have a look into this, how long are your movies and do they have a compressed header for optimized web use? Could be the its time for an omxplayer update...
