### ISSUE TITLE
conflict between power on and schedule

### ISSUE THREAD

**Issue by Mingual123** [magdesign/PocketVJ-CP-v3#50]
When time schedule is programmed to start at 6 o clock and the Raspberry is switched on later like 8 o `clock than no video is being played. it should look in the time schedule to "see" which video is supposed to be played.

**Comment by magdesign** [comment]
This is a logical issue.
When you set your alarm clock to 6 am, but there is no battery in the clock until 8 am, it will not start to ring when you insert the battery. 
To solve this, just set the `Autostart` behavior to  `VideoplayerMaster` so the PocketVJ will start to play a video as soon as it gets power. When the Scheduler is set to on, it will always work, no matter what the `Autostart` behavior is.
Since the Scheduler is based on cronjobs (https://en.wikipedia.org/wiki/Cronjobs), you could also program it to repetitively send the play command every hour.  

BTW. Why would you power of the PocketVJ when you can program it to just stop the movie until the next morning.

**Comment by Mingual123** [comment]
thanks! 
I need to power of the raspberry because the display is still on and lights of the displays are disturbing during the night. I will have a clock timer for all electric machines in the room. since the installation takes 4 weeks and can be nessesary to save power since the displays are no 24/7 displays. they must be plugged of from time to time.

**Comment by Mingual123** [comment]
But the main problem is that the time of raspberry is set to CET and not RTC. After plugging the power of the rapberry it doesnt remember the time after booting. after 6 houres interruption. the "new" time on hardware and software is calculated minus 6 hours. so instead of 12:00 6.02. 2018 it is 06:00 6.2. 2018

**Comment by magdesign** [comment]
The issues you are having are Raspberry related.
Please use this forum for RPi related questions: https://www.raspberrypi.org/forums/

**Comment by Mingual123** [comment]
BTW what is the command to force the display to sleep, it could be very usefull to insert it in the schedule!

**Comment by magdesign** [comment]
its:
sudo /opt/vc/bin/tvservice -o
