### ISSUE TITLE
Video does not overlay the entire screen after startup

### ISSUE THREAD

**Issue by moh-maya** [magdesign/PocketVJ-CP-v3#56]
![img_20180711_173314](https://user-images.githubusercontent.com/21104700/42694639-b88df1cc-86d0-11e8-9fab-a182b6ef90fc.jpg)

Hello,

First, thank you for making this open source, and allowing us to try & test the system! 

We are trying to use PocketVJ to run 3 displays simultaneously. We've successfully built the application and are able to sync videos across the 3 devices (with minor issues).

The primary issue as of now is (as the attached image shows), when the test video plays after boot up (the video starts automatically), it apparently either:

a) Does not seem to refresh the screen, so the initial bash prompt is still visible
b) The video is resized.

The video resolution is 1920x 1080, and that's the maximum resolution of the monitors we are using. 

Note that this issue does not occur if, after startup & the command prompt coming up, I manually click play.

Would appreciate any hints on how I can fix this. We are also facing another issue stopping videos / syncing slaves, but that's currently a lower priority challenge.

As an aside, I sent an email at info@magdesign.ch offering to assist with writing the manual; this project is very promising, and I'd be glad to pitch in & support (in addition to buying a device from your site).

Thank you! :)

**Comment by magdesign** [comment]
Since you are using a PocketVJ built from scratch, I can not tell exactly what is going wrong on your personal setup.
For me it looks like the resolution of the video does not match the resolution of the screens.
Otherwise you would not have it cropped on top and buttom. Try it with a video which is 1920x1080.
Then make sure you set the boot/config.txt file right so it will force the desired resolution on startup.

Sync issues occur mostly if you do not have the exact same setup, e.g. same SD cards, same monitors, same resolution, same cables.

**Comment by moh-maya** [comment]
Thank you; We'll try editing the boot file & see what happens. I think it may do the trick, since this issue only occurs right after booting. If we trigger the videos manually, it goes full screen. 

I'll update this soon once we test.

Thanks again :)
