### ISSUE TITLE
Is it possible to cross compile Pocket VJ on Linux Ubuntu 16.04? 

### ISSUE THREAD

**Issue by simspace-dev** [magdesign/PocketVJ-CP-v3#59]
I want to play around with Pocket VJ to see if it would be a good solution for a part of my band's live video production. 

I saw I can purchase the app on an SD card for RasPi 3. But, for now I only have (3) RasPi Zero W's. 

I've tried building Pocket VJ on my RasPi Zero W with no success.

Is it possible to cross compile Pocket VJ on Linux Ubuntu 16.04, then scp the binary to my RasPi Zero W?

**Comment by magdesign** [comment]
Since there is nothing really to compile there is no cross-compile option.
You have to make all the configurations on the hardware you want to use it.
If wanted, I can modify the SD image so it will  run on a zerow, just drop me an email after ordering. The zeros are a bit slow thats why I never made an official zero release.
