### ISSUE TITLE
how to specify a spout/syphon from multiple sources

### ISSUE THREAD

**Issue by harveymoon** [magdesign/PocketVJ-CP-v3#60]
I have multiple spout sources on the network.
PocketVJ seems to automatically attach to one source and not let go until it is turned off.

How can I specify the input source from a list of network input sources on the PocketVJ v3?

**Comment by magdesign** [comment]
You have to modify ` /var/www/sync/tcpsserver`

and change on line 8:
`sudo -u pi /usr/bin/TCPSClient.bin &`

to something like `sudo -u pi /usr/bin/TCPSClient.bin -c 192.168.2.130 -p 7778 &`

I never tried this so far since I did not know that it is possible to send several Syphon streams over the same network. Please report back if this is working so I can think about implementing a select source button in CP.

There you find some more infos about TCPS flags:
https://github.com/z37soft/INetSyphon_RaspberryPi_SDK

**Comment by xuanhuong184** [comment]
You can make tutorial video how to connnect PocketVj with Spout in Windows.

**Comment by magdesign** [comment]
Get the Syphon/Spout servers here:
[SyphonServer OSX](https://pocketvj.com/downloads/syphon.zip)
[SpoutServer Win](https://pocketvj.com/downloads/TCPSpout.zip)

Make sure to disable Firewall.

Maybe someone here has some info concerning Spout.
I guess its similar to the OSX approach: https://vimeo.com/192291861

**Comment by magdesign** [comment]
Since **Syphon/Spout** is officially not supported on OSX and WIN anymore, you could solve this also with the VNC Screensharing solution:

On Ubuntu I do it like this:
1.) Connecting an AVer Media gameplay recorder to my laptops HDMI output
2.) Starting the "Screenshare" function in PocketVJ
3.) Wifi connect to PocketVJ
4.) In the Ubuntu terminal start the screensharing of the second monitor with:
`vnc4server -connect 2.0.0.100:5500`
`x11vnc -connect 2.0.0.100:5500 -clip 1920x1080+1920+0`
(The -clip options crops the output to 1920x1080 and moves the crop window to the 2nd screen with +1920+0  You might change the numbers if you have other resolutions).
5.) Setup the mapping and then directly record it with the recorder to upload to the PocketVJ.

I think under WIN you could use TighVNC for the reverse connection and define the 2nd  screen with a similar option.
