### ISSUE TITLE
Some questions about DMX

### ISSUE THREAD

**Issue by missqso** [magdesign/PocketVJ-CP-v3#91]
Hi ,
I want to know if PVJ can do these :
1.  Local server sends  osc or tcp signal to PVJ.
2. Control video switching through osc or tcp signals, while controlling the light through DMX.
3. Control the lighting animation through video footage (similar to madmapper)
or Control the lighting animation by select prepared DMX sequence.

Because in my case, I will use a lot of hardware players, after the external control signal comes in, call different video or light animations.

In the current documents, I think that PVJ's dmx is a real-time control panel, not a playback player?

thank you.

**Comment by magdesign** [comment]
1. The PocketVJ is fully controllable with osc and tcp signals
see page 28 and 29 in manual: https://pocketvj.com/pdf/manual3.pdf

2. Video switching with osc/tcp is possible. About the DMX feature, I am currently under heavy development of an DMX recorder/player since the current solution does not support looping 
and sequence change.  To be announced soon, stay tuned!

3. This is not planned, but  you will get the feature to record the light-mapping scene from madmapper, mapio, grandma or whatever and play it back later on.

**Comment by magdesign** [comment]
I just received an Enttec usb pro device to test my dmx code, currently I can tell you this:

Yes, there will be the option to record dmx from any dmx sender (madmapper or anything else) and 
yes, there will be a dmx playback of the recorded show, and
yes you will be able to play a video while playing the dmx file.....

...now I need to finish the code...

**Comment by missqso** [comment]
Thanks for your work. I am looking forward to new funciton.

**Comment by magdesign** [comment]
https://github.com/kr15h/ofxPiMapper/issues/165

**Comment by magdesign** [comment]
DMX recording and playback: https://vimeo.com/370950187
DMX remote control: https://vimeo.com/402281440
