### ISSUE TITLE
Jerky video, lagging of mouse in mapping mode when playing 1080p video(s)

### ISSUE THREAD

**Issue by dingobiscuit** [magdesign/PocketVJ-CP-v3#99]
Hi there,

I have been having some trouble with getting smooth video in mapping mode.
I can play 1280x720p videos pretty smoothly, up to 15Mbps, two at once at present. 

However, I can't get any 1080p videos to play smoothly, even at 10Mbps. 
I have jerky playback with a single video or multiple videos in mapping mode.
When the lag occurs the mouse cursor is laggy and sometimes the audio will cut out if there is audio.

I have no problems playing 1080p videos in the dedicated video player, just have issues in the mapper.
I have forced the resolution to 1080p/720p as a test just in case, but that has not effected the playback.

I have encoded tests in both Adobe Media Encoder and Handbrake.

1080p encode settings are:

H264
1920x1080
10Mbps
160kbps audio
No metadata

When copied to Pocket VJ CP I have used:
Permission fixer
Filename fixer
Clean files

Thanks for reading!

Jesse

**Comment by magdesign** [comment]
The mapper in PocketVJ RTC works best with 1280 x 720p as written in the [documentation](https://www.pocketvj.com/manual_rtc/08_mapping.html).

Sometimes 1920x1080 videos work fluent after they looped once in Present mode.
Also make sure there is an audio channel in the video, even if it is empty, and make it has a low bitrate and no more than stereo channels.
Otherwise use 720p videos.
Sometimes I do the mapping, use a testscreen image instead of the video, use the screenshot function, grab the screenshot and
rebuild the scene in Natron or Resolve, render it there and export a movie to PocketVJ ( I guess I should make a video tutorial on this :-).

The Exhibition has a more performant and completely rewritten mapper, but I am not able to port it to RTC since there are too many system changes.
